env:
  global:
    - CC_TEST_REPORTER_ID=921d046db793707b7d0c0d1305970a137fdf98fbc6ceeb6c355c44757040244f
sudo: false
language: ruby
rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
before_install:
  - gem install -v 2.1.4 bundler
  - bundle _2.1.4_ install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
